Book-Store : Setup
tajulafreen/Book-Store pull request #1
Opened 2023-07-20 19:40 UTC by tajulafreen

**In this PR I did the following:**
- Used React to create an App
- No linter errors.
- Added 2 routes in the application, each should render a page component:
`/`
`/categories`
- Created components inside of the `/components` directory:
- Contains individual book states, as well as a button to delete the book
- Contains a list to render individual books
- Contains a form to create new books
- Contains navigation to link to the 2 routes you created

2023-07-20 21:42 UTC, Munsa1 requested changes
Hi @tajulafreen, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Used React Router Dom For Routing :heavy_check_mark: 
Added Two Routes :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-20 21:42 UTC, Munsa1 commented on README.md
> +- LinkedIn: [@tajul-afreen-shaik-843951251](https://www.linkedin.com/in/tajul-afreen-shaik-843951251/)
- [ ] The link to your `LinkedIn` profile is broken, kindly fix it for a professional readme file.
![image](https://github.com/tajulafreen/Book-Store/assets/81932478/57f15ba4-f13f-49af-97df-cd66bcd7d81b)

2023-07-20 21:42 UTC, Munsa1 commented on README.md
> +
- [ ] (optional) It's up to you how much in detail you want to go into about each section, but I would encourage you to remove this command here `npm install` as this command is for setting up the app. Rather you could put the software needed to run this app here such as :

```
- Node.js
- Vscode
- Current Web Browser
```
These are what we call prerequisites.

2023-07-20 21:42 UTC, Munsa1 commented on README.md
> +
- [ ] (optional) Here again I would encourage you to remove these commands and add the `npm install` command as that is all you need to install the dependencies needed to run the project.

2023-07-20 21:42 UTC, Munsa1 commented on README.md
> +  - [🚀 Live Demo](#live-demo)
- [ ] Kindly remove the `Live Demo` link from the table of contents as it points to a section that has been removed, making it a broken link.

2023-07-20 21:42 UTC, Munsa1 commented on src/components/booklist.js
> +export default Booklist;
- [ ] The `booklist` component should Render a list of books using the `Book` component. Kindly do so instead of creating an array here and looping through it to display a list of books.
![image](https://github.com/tajulafreen/Book-Store/assets/81932478/078ec53a-15e3-43dc-a440-07ce197dc1bf)
If you check the second requirement it stipulates that the list should render individual books. You can add the array to the book component and map it there so that each individual book shows with a delete button in the `booklist` component.
Check the requirements [here](https://github.com/microverseinc/curriculum-react-redux/blob/main/bookstore/project_init_project_wth_comps_v3_0.md)

### Important :red_circle: 
- [ ] Kindly ensure that each book has a delete button, it does not have to be functional for now but it has to he present with each book

2023-07-20 21:42 UTC, Munsa1 commented on src/App.js
> +          </Routes>
- [ ] Kindly note that you have to create another component that will hold all your book-related components. That's the component that will be imported here, not the `booklist` component.
So, your `book` component will be imported into the `booklist` component to display individual book items in a list. then the `booklist` and the `input` component will be imported into the new component you will create which will then be imported into the main component, the `App.js`.

2023-07-20 21:42 UTC, Munsa1 commented on src/components/book.js
> +export default Book;
- [ ] The book component should take the book data as a prop and render the title and the author as per requirement. Kindly do so.

The following is just an example:

```
import React from 'react';
import PropTypes from 'prop-types';

const BookItem = ({ book }) => {
  const {
    booktitle, author, id, category,
  } = book;
  return (
    <li key={id}>
      <p>
        Book:
        {booktitle}
      </p>
      <p>
        Author:
        {author}
      </p>
      <p>
        Category:
        {category}
      </p>
      <button type="button" itemID={id}>Remove</button>
    </li>
  );
};

BookItem.propTypes = {
  book: PropTypes.shape(
    {
      booktitle: PropTypes.string.isRequired,
      id: PropTypes.string.isRequired,
      author: PropTypes.string.isRequired,
      category: PropTypes.string.isRequired,
    },
  ).isRequired,
};

export default BookItem
```

2023-07-21 15:17 UTC, joskalenda approved these changes
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @tajulafreen , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
| <img src="https://media2.giphy.com/media/2NpKgBuUZtXpu/giphy.gif"/> |

### Highlights
✅ ... Great design
✅ ... Green linters

---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 15:53 UTC, merged